#!/bin/sh


if [ -f /usr/yaffs/etc/net.conf ] ; then
	source /usr/yaffs/etc/net.conf

	ifconfig eth0 down
	ifconfig eth0 hw ether $MAC

	ifconfig eth0 $IPADDR netmask $NETMASK up

	route add default gw $GATEWAY

else

	ifconfig eth0 hw ether 10:23:45:67:89:ab
	ifconfig eth0 192.168.1.88 netmask 255.255.255.0 up
	route add default gw 192.168.1.1
	telnetd

fi

echo net_set Done!
